apiVersion: apps/v1
kind: Deployment
metadata:
  name: deprdemo
  labels:
    app: deprdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deprdemo
  template:
    metadata:
      labels:
        app: deprdemo
        name: deprdemo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "deprdemo"
    spec:
      containers:
        - name: deprdemoport
          image: registry.cn-hangzhou.aliyuncs.com/zhangqihang/dapr:test
          ports:
            - containerPort: 8080