apiVersion: apps/v1
kind: Deployment
metadata:
  name: deprdemo
  labels:
    app: deprdemo
    name: deprdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deprdemo
  template:
    metadata:
      labels:
        app: deprdemo
        name: deprdemo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "deprdemo"
    spec:
      containers:
        - name: deprdemoport
          image: dapr:test
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deprdemo-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30521
      protocol: TCP
  selector:
    name: deprdemo